### ISSUE TITLE
Issue and pull request templates

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/opensource#64]
Implement organisation-wide issue and PR templates - see https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

- Link to Discourse _(forum)
- Link to Discord (chat)

## Tasks

- [x] create `.github` repo. See [here](https://github.com/inveniosoftware/.github)
- [x]  fill in the README
- [x] create the following templates: issues/pull request/config.yml

## Questions

Does it make sense to add the following or not? (see full list [here](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types)):
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
- SUPPORT.md
