### ISSUE TITLE
community: investigate creation of webinars/micro-workshops

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/opensource#66]
Stems from https://github.com/inveniosoftware/opensource/issues/62

Guiding principles:
- Audience: What are the specific groups of interest?
- Searchability, exposure: Can we make it useful not only for the live event but also for people coming after?
- Openly documented process: How could this be technically achieved?
- Community-driven: Can someone outside CERN take the organization over?

Materialize an implementation plan:
- [x] Find a technical implementation to: stream content live, record it and publish it
    - [x] Automate/document the process
    - [x] Create a maintainance documentation
- [x] Choose where should this be promoted (inveniosoftware.org new docs page?)
- [ ] Create a survey to identify potential content to be created
- [ ] Create a demonstrator (if time permits)

---

A couple of examples of finished products:
- Kubernetes webinars by CERN Cloud team: [zoom webinar](https://zoom.us/webinar), live + recording published to videos.cern.ch e.g. [Kubernetes High Availability for Services and Control Plane](https://videos.cern.ch/record/2718629) (we can ask how this is specifically done in [their Mattermost channel](https://mattermost.web.cern.ch/it-dep/channels/cloud-containers
)).
- OpenShift webinars: https://www.openshift.com/learn/resources/webinars
- ...

**Comment by FlorianCassayre** [comment]
https://codimd.web.cern.ch/oVHk3fkRQa2SmonokeOK8A

**Comment by FlorianCassayre** [comment]
### Tasks
(_do not hesitate to copy/paste this comment in a new issue_)

- Preliminary steps
  - [ ] Think about which category of people you want to target first (institutions, end users, developers and contributors). You can materialize this as a weighted resources allocation plan (how much energy you are willing to invest for each of the categories)
  - [ ] What content would you like to cover in these resources? Make a list of topics that would like to include, and sort them by order of importance
  - [ ] Decide how you will split and present the chosen topics (= design the story)
- Support and format
  - [ ] Choose the format to adopt (step by step tutorial ["design your own" style], sample usage by a user, overall demonstration of the capabilities, developer demonstration [eg. creating a module])
  - [ ] Decide the medium (webinar with replay, pre-recorded video, workshop, other?)
    You can create different combinations
- Promotion
  - [ ] Decide where and how this should be promoted (organization website, documentation, network, ...)
- Creation
  - [ ] Sketch the scenarios, **let peers review them**. This is probably an iterative task
  - [ ] Set the stage
    - For webinars/videos/demos: prepare and organize your environment such that you can clearly present what you want to
    - For tutorials/workshops: prepare the user tools (skeleton repository, VM, documentation)
  - [ ] Record/Write it
- Publication and promotion
  - [ ] Host the conferences, supervize the workshops, publish the videos
  - [ ] Advertize the future webinars/workshops, promote the published videos/tutorials. **Important advice**: do not rush this task! A well advertized resource of average content may have a more positive effect than a good but poorly advertized one

**Comment by ppanero** [comment]
It is an impressive job @FlorianCassayre! My 2 cents:

> provides a ready-to-use VM

This has proven to be slow and give maaaany troubles lately. So it might need to be updated, I don't think is belongs to the scope of this task... but if we aim at developers they should install a dev setup, on the other hand for end users... they could use the `invenio-cli` (only integrated to RDM for now). TBDiscussed, just wanted to point out the VM is not really in good shape atm.

**Comment by FlorianCassayre** [comment]
This was only given as an example of a task to do for this bullet, but it's great that you already have feedback from past experiences to guide such decisions! :+1:
I'll update the description to avoid confusion.

**Comment by saragon02** [comment]
Closing as part of repo updates, May 2024
